services:
  - type: web
    name: turkish-word-finder
    env: python
    region: oregon
    plan: free
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      
      # Install and build frontend assets
      npm install
      echo "Building CSS..."
      npm run build
      
      # Verify CSS build
      echo "Verifying CSS build..."
      if [ ! -f "app/static/css/main.css" ]; then
        echo "Error: main.css was not generated"
        exit 1
      fi
      
      # List CSS files for verification
      echo "CSS files in app/static/css/:"
      ls -la app/static/css/
      
      # Ensure proper permissions
      chmod -R 755 app/static/css/
    startCommand: |
      export PYTHONPATH=$PYTHONPATH:$(pwd)
      gunicorn wsgi:app --workers 2 --bind 0.0.0.0:$PORT --timeout 120
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: wsgi.py
      - key: NODE_ENV
        value: production
      - key: TAILWIND_MODE
        value: build